version: '3.7'

services:
  web:
    network_mode: "host"
    build: ./heckatlonbackend
    command: python manage.py runserver localhost:8000
    volumes:
      - ./heckatlonbackend:/usr/src/app/
    # ports:
    #   - 8000:8000
    env_file: .env
