version: '3.7'

services:
  web:
    build: ./heckatlonbackend
    command: gunicorn heckatlonbackend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file: .env
    volumes:
      - static_volume:/usr/src/app/static
    networks:
      - default
      - databasenetwork

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/static
    networks:
      - default

volumes:
  static_volume:

networks:
  default:

  databasenetwork:
    external:
      name: postgres_databasenetwork
