version: '3.7'

services:
  web:
    build: ./heckatlonbackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./heckatlonbackend:/usr/src/app/
    ports:
      - 8000:8000
    env_file: .env
