# Generated by Django 2.2.4 on 2019-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20190817_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
