# Generated by Django 2.2.4 on 2019-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20190818_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_name',
            field=models.TextField(null=True),
        ),
    ]
