# Generated by Django 2.2.4 on 2019-08-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_recipeingredient_ingredient_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient', 'quantity', 'unit')},
        ),
    ]
