# Generated by Django 2.2.4 on 2019-08-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_auto_20190818_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='foods.Ingredient'),
        ),
    ]
